### ISSUE TITLE
fix: 서버 요청 줄이기

### ISSUE THREAD

**Issue by YesHyeon** [dnd-side-project/dnd-8th-5-frontend#71]
## AS IS

불필요하게 서버에 API 요청을 하는 문제를 해결하고자 합니다.
ex) 실시간 조율 현황 페이지에서 Room 정보를 불러왔는데, 로그인 페이지에서도 불러오는 문제

**Comment by corinthionia** [comment]
이건 전체적으로 다 수정해야 할 것 같아서,,
나중에 시험 끝나고 리팩토링 방향 한번 더 구체적으로 논의해 보는 게 좋을 것 같아욥
