### ISSUE TITLE
fix: 6월 22일 QA 수정사항 (방생성 일정등록, 시작페이지, 바텀시트)

### ISSUE THREAD

**Issue by YesHyeon** [dnd-side-project/dnd-8th-5-frontend#86]
## AS IS

6월 22일에 진행한 QA 수정사항은 다음과 같습니다.

[방 생성 일정등록]
- [x] 기간 선택 후 하나씩 선택으로 변경할 때 실제 데이터도 변경되지 않는 문제
- [x] 기간 선택 후 하나씩 선택으로 변경할 때 화면상으로 선택이 초기화되지 않는 문제
- [x] 기간 선택하고 취소시 클릭이 밀리는 문제 (모바일)
- [x] 캘린더의 빈공간이 클릭되는 문제
- [x] 현재 날짜 이전 날짜가 클릭되는 문제 (모바일)
- [x] 월변경시 hover 속성이 유지되는 문제

[시작페이지]
- [x] 시작페이지 배경 중간정렬 맞지않는 문제 

[공유하기 바텀시트]
- [x] 공유하기 바텀시트 바텀이 바로 사라지지 않는 문제

**Comment by corinthionia** [comment]
PR에 `resolve #이슈번호` 남기면 PR 머지 시 이슈가 자동으로 닫힙니다!
